# This is the configuration file for pre-commit hooks.
repos:
  # Pre-commit hooks repository with common checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Always use the latest stable version (check GitHub for updates)
    hooks:
      - id: trailing-whitespace # Removes trailing whitespace
      - id: end-of-file-fixer # Ensures files end with a newline
      - id: check-yaml # Checks that YAML files are properly formatted
      - id: check-added-large-files # Prevents large files from being added to the repository

  # flake8 is a popular linter for Python projects
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1 # Choose the appropriate version of flake8
    hooks:
      - id: flake8 # Lints Python files and enforces style

  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 23.7.0 # Use the appropriate version of Black
    hooks:
      - id: black # Automatically formats Python code

  # JSON linting
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.57.0
    hooks:
      - id: terraform_fmt
        args: ["-recursive"] # Ensures that Terraform files are formatted properly
      - id: terraform_validate
        args: ["-no-color"] # Validates Terraform files


  # Add more repositories and hooks as needed for your project
